version: "3"
services:
  builder:
    build:
      context: ..
      dockerfile: docker/builder.dockerfile
  buster:
    depends_on: 
      - builder
    build:
      context: ..
      dockerfile: docker/test.buster.dockerfile
  bionic:
    depends_on: 
      - builder
    build:
      context: ..
      dockerfile: docker/test.bionic.dockerfile
  # stretch:
  #   depends_on: 
  #     - builder
  #   build:
  #     context: ..
  #     dockerfile: docker/test.stretch.dockerfile
  # xenial:
  #   depends_on: 
  #     - builder
  #   build:
  #     context: ..
  #     dockerfile: docker/test.xenial.dockerfile
