#!/bin/sh
set -e # lintian wants this script to exit when there are errors

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule

    # source dbconfig-common shell library, and call the hook function
    if [ -f /usr/share/dbconfig-common/dpkg/postrm.mysql ]; then
      . /usr/share/dbconfig-common/dpkg/postrm.mysql 
      dbc_go concerto-full $@
    fi

    # Remove my changes to the db.
    db_purge
fi

update-rc.d -f concerto remove

# remove the entire application directory if purging
if [ "$1" = "purge" ]; then
  if [ -d /usr/share/concerto ]; then
    rm -rf /usr/share/concerto
  fi
fi

apache2ctl start
