#!/bin/sh
#set -e

#Source debconf library.
. /usr/share/debconf/confmodule

db_get concerto/passenger
passenger="$RET"

if [ "$passenger"  = "true" ]; then
  gem1.9.1 install --no-ri --no-rdoc passenger -v 3.0.18
  cd /var/lib/gems/1.9.1/gems/passenger-3.0.18
  rake apache2
fi

gem1.9.1 install --no-ri --no-rdoc rake bundler highline

#We'll leave database.yml alone if it exists already
if [ ! -f /usr/share/concerto/config/database.yml ];
then
  cp /usr/share/concerto/config/database.yml.sample /usr/share/concerto/config/database.yml
fi
mkdir /usr/share/concerto/tmp
chmod -R 777 /usr/share/concerto/tmp
chown -R www-data:www-data /usr/share/concerto
chmod 775 /usr/share/concerto/config/database.yml

cd /usr/share/concerto
bundle install --path=vendor/bundle

apache2ctl restart
