#!/bin/sh
set -e # lintian wants this script to exit when there are errors

#Source debconf library.
. /usr/share/debconf/confmodule

# source dbconfig-common shell library, and call the hook function
if [ -f /usr/share/dbconfig-common/dpkg/prerm.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/prerm.mysql 
  dbc_go concerto-full $@
fi

a2dissite concerto
apache2ctl restart

invoke-rc.d concerto stop
update-rc.d -f concerto remove
