#!/bin/sh
set -e # lintian wants this script to exit when there are errors

#Source debconf library.
. /usr/share/debconf/confmodule

# source dbconfig-common shell library, and call the hook function
if [ -f /usr/share/dbconfig-common/dpkg/prerm.mysql ]; then
  . /usr/share/dbconfig-common/dpkg/prerm.mysql 
  dbc_go concerto-full $@
fi

a2dissite concerto
apache2ctl restart

invoke-rc.d concerto stop
update-rc.d -f concerto remove

# remove the files that were generated after the install if we are purging
if [ "$1" = "purge" ]; then
  if [ -d /usr/share/concerto/vendor ]; then
    rm -rf /usr/share/concerto/vendor
  fi
  if [ -d /usr/share/concerto/public ]; then
    rm -rf /usr/share/concerto/public
  fi
  if [ -f /usr/share/concerto/config/database.yml ]; then
    rm /usr/share/concerto/config/database.yml
  fi
fi
