#!/bin/sh
set -e

#Source debconf library.
. /usr/share/debconf/confmodule

gem1.9.1 install --no-ri --no-rdoc rake bundler highline

cd /usr/share/concerto
bundle install --without development --path vendor/bundle

#We'll leave database.yml alone if it exists already
if [ ! -f /usr/share/concerto/config/database.yml ];
then
  cp config/database.yml.sample config/database.yml
fi
mkdir tmp
chmod -R 777 tmp
chown -R www-data:www-data /usr/share/concerto
