#!/bin/sh
set -e

#Source debconf library.
. /usr/share/debconf/confmodule

gem1.9.1 install --no-ri --no-rdoc rake bundler highline

#We'll leave database.yml alone if it exists already
if [ ! -f /usr/share/concerto/config/database.yml ];
then
  cp /usr/share/concerto/config/database.yml.sample /usr/share/concerto/config/database.yml
fi
mkdir /usr/share/concerto/tmp
chmod -R 777 /usr/share/concerto/tmp
mkdir -p /usr/share/concerto/log 
chown -R www-data:www-data /usr/share/concerto
chmod 775 /usr/share/concerto/config/database.yml

cd /usr/share/concerto
bundle install --without development --path=vendor/bundle

update-rc.d concerto defaults
invoke-rc.d concerto start
