#!/bin/sh
set -e

#Source debconf library.
. /usr/share/debconf/confmodule

gem1.9.1 install --no-ri --no-rdoc rake bundler

#We'll leave database.yml alone if it exists already
if [ ! -f /usr/share/concerto/config/database.yml ];
then
  cp /usr/share/concerto/config/database.yml.sqlite /usr/share/concerto/config/database.yml
fi
mkdir -p /usr/share/concerto/tmp
chmod -R 777 /usr/share/concerto/tmp
mkdir -p /usr/share/concerto/log 
chown -R www-data:www-data /usr/share/concerto
chmod 775 /usr/share/concerto/config/database.yml

cd /usr/share/concerto
sudo -u www-data bundle install --without development --path=vendor/bundle
sudo -u www-data RAILS_ENV=production bundle exec rake assets:precompile
sudo -u www-data bundle clean -V

update-rc.d concerto defaults
invoke-rc.d concerto start
