#!/bin/sh
set -e

#Source debconf library.
. /usr/share/debconf/confmodule

gem1.9.1 install --no-ri --no-rdoc rake rmagick bundler
gem1.9.1 install --no-ri --no-rdoc passenger -v 3.0.12
/etc/passenger-install.sh
cd /usr/share/concerto
bundle install --path vendor/bundle
rake db:migrate
rake db:seed
