#!/bin/sh
set -e

#Source debconf library.
. /usr/share/debconf/confmodule

gem1.9.1 install --no-ri --no-rdoc rake rmagick bundler
gem1.9.1 install --no-ri --no-rdoc passenger -v 3.0.12
cd /var/lib/gems/1.9.1/gems/passenger-3.0.12
rake apache2
cd /usr/share/concerto
bundle install --path vendor/bundle
cp config/database.yml.sample config/database.yml
mkdir tmp
chmod -R 777 tmp
rake db:migrate
rake db:seed
